import { test, expect } from '@playwright/test'
import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
const require=createRequire(import.meta.url)
const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, ImageRun } = require('docx')
const JSZip = require('jszip')

const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='
const html=`<html><head><title>Guide</title></head><body><nav><a href="/menu">Site menu</a></nav><main><h1 id="intro">Import Guide</h1><p>Original paragraph with <code>inline</code> and <strong>bold</strong>.</p><p>Remove this paragraph.</p><ul><li>First item</li><li>Second item</li></ul><pre><code class="language-js">const sample = 42;\nconsole.log(sample);</code></pre><table><thead><tr><th>Name</th><th>Value</th></tr></thead><tbody><tr><td>Item</td><td>0012</td></tr></tbody></table><figure><img src="data:image/png;base64,${png}" alt="Diagram"/><figcaption>Architecture caption</figcaption></figure><aside class="admonition"><p><strong>Warning</strong></p><p>Keep your changes.</p></aside><script>window.evil=true</script><p onclick="window.evil=true">Safe text</p></main><footer>Unrelated footer</footer></body></html>`

test('dark reading overrides source light surfaces for inline code, fences and document layers',async({page})=>{
  await page.goto('/')
  const sample='# Dark document\n\nInline `text`\n\n```js\nconst answer = 42\n```\n\n<div style="background-color:white;color:black"><p>A light panel</p><code style="background-color:white;color:black">inline HTML</code></div>\n\n<style>body{color:black}code,pre{background-color:#ffffff;color:#000000}div{background-color:white}</style>'
  await page.getByRole('textbox',{name:'Try Markdown'}).fill(sample)
  await page.evaluate(async()=>{const {useSettingsStore}=await import('/src/stores/settingsStore.ts');useSettingsStore.getState().setTheme('dark')})
  const inline=page.locator('.markdown-content p code').first()
  await expect(inline).toHaveCSS('background-color','rgb(28, 29, 39)')
  await expect(inline).toHaveCSS('color','rgb(238, 240, 248)')
  await expect(page.locator('.markdown-content pre')).toHaveCSS('background-color','rgb(28, 29, 39)')
  await expect(page.locator('.markdown-content .hljs-keyword').first()).toHaveCSS('color','rgb(139, 161, 255)')
  await expect(page.locator('.markdown-content div[style]')).toHaveCSS('background-color','rgba(0, 0, 0, 0)')
  await page.emulateMedia({colorScheme:'dark'})
  await page.evaluate(async()=>{const {useSettingsStore}=await import('/src/stores/settingsStore.ts');useSettingsStore.getState().setTheme('system')})
  await expect(inline).toHaveCSS('background-color','rgb(28, 29, 39)')
  await page.emulateMedia({colorScheme:'light'})
  await expect(inline).toHaveCSS('background-color','rgb(255, 255, 255)')
  await page.emulateMedia({colorScheme:'dark'})
  await page.getByRole('textbox',{name:'Try Markdown'}).fill(readFileSync('../documentation/05-robot-dashboard.md','utf8'))
  await expect(page.locator('.markdown-content code').first()).toHaveCSS('background-color','rgb(28, 29, 39)')
})

test('HTML review edits, excludes, restores and exports through the existing converter',async({page})=>{
  await page.goto('/import')
  await page.getByRole('button',{name:/^HTML/}).click()
  await page.getByLabel('Paste HTML',{exact:true}).fill(html)
  await page.getByRole('button',{name:'Parse & review',exact:true}).click()
  const review=page.getByRole('region',{name:'Custom Preview'})
  await expect(review).toBeVisible()
  await expect(review.locator('.markdown-content h1')).toHaveText('Import Guide')
  await expect(review.locator('.markdown-content')).not.toContainText(['Site menu','Unrelated footer'])
  expect(await page.evaluate(()=>('evil' in window))).toBe(false)
  await expect(review.locator('.markdown-content img')).toBeVisible()
  expect(await review.locator('.markdown-content img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(1)
  await page.getByRole('button',{name:'Edit blocks',exact:true}).click()
  const blocks=review.locator('article[id]'), paragraph=blocks.nth(1), stable=await paragraph.getAttribute('id')
  await paragraph.getByRole('button',{name:'Edit',exact:true}).click()
  await page.getByRole('textbox',{name:'Edit block 2',exact:true}).fill('Reviewed **content** with `code`.')
  expect(await paragraph.getAttribute('id')).toBe(stable)
  await page.getByRole('checkbox',{name:'Keep block 3',exact:true}).uncheck()
  await page.getByRole('button',{name:'Remove block 4',exact:true}).click()
  await expect(blocks.nth(3)).toContainText('Removed from output')
  await blocks.nth(3).getByRole('button',{name:'Restore',exact:true}).click()
  await page.getByRole('button',{name:'Move block 4 up',exact:true}).click()
  await expect(blocks.nth(2).locator('.markdown-content')).toContainText('First item')
  await page.getByRole('button',{name:'Markdown',exact:true}).click()
  await page.getByText('Original HTML',{exact:true}).click()
  await expect(review.locator('details pre')).toContainText('Site menu')
  await expect(review.locator('details pre')).not.toContainText('<script>')
  await page.getByRole('button',{name:'More formats',exact:true}).click()
  await expect(page.getByRole('button',{name:'Open Converter',exact:true})).toBeDisabled()
  await expect(page.getByRole('button',{name:'Confirm review',exact:true})).toBeEnabled({timeout:30000})
  await page.getByRole('button',{name:'Confirm review',exact:true}).click()
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download .md',exact:true}).click()
  const md=readFileSync((await (await download).path())!,'utf8')
  expect(md).toContain('Reviewed **content**');expect(md).toContain('```js');expect(md).toContain('| Name | Value |');expect(md).not.toContain('Remove this paragraph')
  await page.getByRole('button',{name:'Open Converter',exact:true}).click()
  await expect(page).toHaveURL(/converter/)
  await page.getByRole('button',{name:'DOCX',exact:true}).click()
  await expect(page.getByRole('button',{name:'Export DOCX',exact:true})).toBeEnabled()
  const word=page.waitForEvent('download');await page.getByRole('button',{name:'Export DOCX',exact:true}).click()
  const zip=await JSZip.loadAsync(readFileSync((await (await word).path())!))
  const xml=await zip.file('word/document.xml')!.async('string')
  expect(xml).toContain('Reviewed');expect(xml).toContain('<w:tbl>');expect(xml).not.toContain('Remove this paragraph')
  expect(Object.keys(zip.files).some(name=>name.startsWith('word/media/')&&!zip.files[name].dir)).toBe(true)
  await page.getByRole('link',{name:'Import',exact:true}).click()
  await expect(page.locator('.markdown-content')).toContainText(['Reviewed content'])
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({path:'.tmp/import-review-mobile.png',fullPage:true})
})

test('DOCX parses native structure and remaps Word styles without uploading',async({page})=>{
  const doc=new Document({styles:{paragraphStyles:[{id:'Code',name:'Code',basedOn:'Normal',run:{font:'Courier New'}},{id:'Caption',name:'Caption',basedOn:'Normal'}]},sections:[{children:[
    new Paragraph({text:'Word Guide',heading:HeadingLevel.TITLE}),new Paragraph({text:'Requirements',heading:HeadingLevel.HEADING_1}),new Paragraph({children:[new TextRun({text:'Bold requirement',bold:true})]}),new Paragraph({text:'npm run build',style:'Code'}),new Paragraph({text:'An image caption',style:'Caption'}),new Paragraph({text:'First bullet',bullet:{level:0}}),new Table({rows:[new TableRow({children:[new TableCell({children:[new Paragraph('Cell A')]}),new TableCell({children:[new Paragraph('Cell B')]})]})]}),new Paragraph({children:[new ImageRun({data:Buffer.from(png,'base64'),type:'png',transformation:{width:20,height:20}})]}),
  ]}]})
  const buffer=await Packer.toBuffer(doc)
  const requests:string[]=[];page.on('request',r=>{if(r.method()==='POST')requests.push(r.url())})
  await page.goto('/import')
  await page.getByRole('button',{name:/Word Document/}).click()
  await page.getByLabel('Choose DOCX',{exact:false}).setInputFiles({name:'guide.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer})
  await page.getByRole('button',{name:'Parse & review'}).click()
  await expect(page.locator('.markdown-content h1').first()).toHaveText('Word Guide')
  await expect(page.locator('.markdown-content pre')).toContainText('npm run build')
  await expect(page.locator('.markdown-content table')).toContainText('Cell A')
  await page.locator('.markdown-content img').scrollIntoViewIfNeeded()
  await expect(page.locator('.markdown-content img')).toBeVisible()
  await page.getByRole('button',{name:'Edit blocks',exact:true}).click()
  await page.getByText('DOCX style mapping',{exact:true}).click()
  await page.getByRole('combobox',{name:'Map Title',exact:true}).click()
  await page.getByRole('option',{name:'h2',exact:true}).click()
  await page.getByRole('button',{name:'Reparse with mappings'}).click()
  await page.getByRole('dialog',{name:'Replace block edits?'}).getByRole('button',{name:'Reparse document',exact:true}).click()
  await expect(page.locator('.markdown-content h2').first()).toHaveText('Word Guide')
  expect(requests).toEqual([])
})

test('documentation discovery stays bounded, selects pages, retains image URLs and keeps review session',async({page})=>{
  const root='https://docs.example.com/guide/', calls:string[]=[]
  await page.route('**/api/import',async route=>{
    const {url,kind}=route.request().postDataJSON();calls.push(url)
    expect(route.request().method()).toBe('POST')
    expect(route.request().headers().authorization).toBeUndefined()
    const html=url===root?'<main><h1>Introduction</h1><p>Welcome.</p><a href="setup.html">Setup</a><a href="setup.html#again">Duplicate</a><a href="https://external.example.com/">External</a><a href="/elsewhere/">Out of path</a><a href="?page=2">Query</a><img src="image.png" alt="Diagram"></main>':'<article><h1>Setup</h1><p>Install this tool.</p><a href="./">Back</a><img src="image.png" alt="Diagram"></article>'
    await route.fulfill({json:kind==='image'?{url,data:`data:image/png;base64,${png}`}:{url,html}})
  })
  await page.route('https://docs.example.com/**',async route=>{
    if(route.request().resourceType()==='fetch')calls.push(route.request().url())
    await route.fulfill({contentType:'image/png',body:Buffer.from(png,'base64'),headers:{'Access-Control-Allow-Origin':'*'}})
  })
  await page.goto('/import')
  await page.getByRole('button',{name:/Documentation Site/}).click()
  await page.getByLabel('Page URL',{exact:true}).fill(root)
  await expect(page.getByLabel('Import access key',{exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Discover pages'}).click()
  const list=page.getByRole('group',{name:'Choose documentation pages (2)'})
  await expect(list).toBeVisible()
  await list.getByRole('checkbox').nth(1).check()
  await page.getByRole('button',{name:'Review selected pages'}).click()
  await expect(page.getByRole('combobox',{name:'Imported document',exact:true})).toBeVisible()
  expect(calls).toEqual([root,root+'setup.html',root+'image.png'])
  await page.getByRole('button',{name:'More formats',exact:true}).click()
  await expect(page.getByRole('button',{name:'Confirm review',exact:true})).toBeEnabled({timeout:30000})
  await page.getByRole('button',{name:'Confirm review',exact:true}).click()
  await page.getByRole('button',{name:'Open Converter',exact:true}).click()
  await expect(page.getByText('2 documents in export order')).toBeVisible()
  await page.getByRole('link',{name:'Import',exact:true}).click()
  await expect(page.getByRole('region',{name:'Custom Preview'})).toBeVisible()
  expect(calls).toHaveLength(3)
})

test('empty HTML and invalid DOCX show actionable errors, and malicious imported HTML never executes',async({page})=>{
  await page.goto('/import')
  await page.getByRole('button',{name:/^HTML/}).click()
  await page.getByLabel('Paste HTML',{exact:true}).fill('<script>alert(1)</script><nav>Menu</nav>')
  await page.getByRole('button',{name:'Parse & review'}).click()
  await expect(page.getByRole('alert')).toContainText('No readable content')
  await page.getByRole('button',{name:/Word Document/}).click()
  await page.getByLabel('Choose DOCX',{exact:false}).setInputFiles({name:'bad.docx',mimeType:'application/octet-stream',buffer:Buffer.from('not a zip')})
  await page.getByRole('button',{name:'Parse & review'}).click()
  await expect(page.getByRole('alert')).toContainText('Not a readable DOCX')
})

test('document tabs rename on double-click or F2 and brand supports native home navigation',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Start writing'}).click()
  const tab=page.getByRole('tablist',{name:'Open documents'})
  await page.locator('.cm-content').fill('# Keep this content')
  await tab.getByRole('button',{name:'Untitled.md',exact:true}).dblclick()
  await page.getByRole('textbox',{name:'Document filename'}).fill('Installation guide')
  await page.keyboard.press('Enter')
  await expect(tab.getByRole('button',{name:'Installation guide.md',exact:true})).toBeVisible()
  await expect(tab.getByRole('button',{name:'Installation guide.md',exact:true}).locator('svg')).toHaveCount(1)
  await expect(page.locator('.cm-content')).toContainText('Keep this content')
  await tab.getByRole('button',{name:'Installation guide.md',exact:true}).focus();await page.keyboard.press('F2')
  await page.getByRole('textbox',{name:'Document filename'}).fill('Cancelled.md');await page.keyboard.press('Escape')
  await expect(tab.getByRole('button',{name:'Installation guide.md',exact:true})).toBeVisible()
  await tab.getByRole('button',{name:'Rename Installation guide.md'}).click()
  await page.getByRole('textbox',{name:'Document filename'}).fill('../bad');await page.keyboard.press('Enter')
  await expect(page.getByRole('alert')).toContainText('valid filename')
  await page.keyboard.press('Escape')
  await page.locator('.cm-content').focus()
  const download=page.waitForEvent('download');await page.keyboard.press('Control+s')
  expect((await download).suggestedFilename()).toBe('Installation guide.md')
  const brand=page.getByRole('link',{name:'Ultimate Markdown home',exact:true})
  await expect(brand).toHaveAttribute('href','/')
  // Headless Chrome suppresses background tabs for middle clicks. Verify the
  // real anchor leaves the native auxiliary-click action available.
  await brand.evaluate(link=>link.addEventListener('auxclick',event=>{queueMicrotask(()=>link.setAttribute('data-middle-prevented',String(event.defaultPrevented)))},{once:true}))
  await brand.click({button:'middle'})
  await expect(brand).toHaveAttribute('data-middle-prevented','false')
  await expect(page).toHaveURL(/workspace/)
  await brand.click();await expect(page).toHaveURL('http://127.0.0.1:5173/')
})


test('URL import preserves modern remote images when CORS blocks image bytes, and opens existing Markdown editor',async({page})=>{
  const root='https://article.example.com/docs/start.html'
  await page.route('**/api/import',async route=>{
    const {url,kind}=route.request().postDataJSON()
    if(kind==='image'){await route.fulfill({status:502,json:{error:'The source image could not be downloaded.'}});return}
    await route.fulfill({json:{url,html:'<nav><img src="logo.png">Navigation</nav><main><h1>Robot Guide</h1><button>Copy page</button><h2 id="requirements"><a href="#requirements" aria-label="Navigate to header">Anchor</a>Requirements</h2><p>Use <code>npm install</code>.</p><figure><picture><source srcset="../small.png 320w, ../large.png 1600w"><img alt="Robot" title="Robot setup" src=""></picture><figcaption>Robot screen</figcaption></figure><img data-src="./lazy.png" alt="Lazy diagram"><ul><li><input type="checkbox" checked>Complete<ul><li>Nested</li></ul></li></ul><pre><code class="language-python">  print("hi")</code></pre><table><tr><td colspan="2">Merged</td></tr></table></main>'}})
  })
  await page.route('https://article.example.com/**',async route=>{
    if(route.request().resourceType()==='fetch'){await route.abort('failed');return}
    await route.fulfill({contentType:'image/png',body:Buffer.from(png,'base64')})
  })
  await page.goto('/import')
  await expect(page.getByRole('textbox')).toHaveCount(1)
  await page.getByLabel('Page URL',{exact:true}).fill(root)
  await page.getByRole('button',{name:'Convert to Markdown',exact:true}).click()
  await expect(page.getByRole('region',{name:'Custom Preview'})).toBeVisible()
  const robot=page.locator('.markdown-content img[alt="Robot"]')
  await robot.scrollIntoViewIfNeeded()
  await expect(robot).toHaveAttribute('src','https://article.example.com/large.png')
  await expect.poll(()=>robot.evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(1)
  await expect(page.locator('.markdown-content img[alt="Lazy diagram"]')).toHaveAttribute('src','https://article.example.com/docs/lazy.png')
  await page.getByRole('button',{name:'More formats',exact:true}).click()
  await expect(page.getByRole('button',{name:'Open in editor',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'Confirm review',exact:true}).click()
  await page.getByRole('button',{name:'Open in editor',exact:true}).click()
  await expect(page).toHaveURL(/workspace/)
  const source=await page.locator('.cm-content').innerText()
  expect(source).toContain('https://article.example.com/large.png')
  expect(source).toContain('*Robot screen*');expect(source).toContain('`npm install`');expect(source).toContain('[x]');expect(source).toContain('```python');expect(source).toContain('colspan="2"');expect(source).not.toContain('logo.png');expect(source).not.toContain('Copy page');expect(source).toContain('## Requirements')
  await expect(page.getByRole('button',{name:'Connect image folder',exact:true})).toHaveCount(0)
  await page.getByRole('link',{name:'Import',exact:true}).click()
  await page.getByRole('button',{name:'Close import session',exact:true}).click()
  await page.getByRole('dialog',{name:'Close this import review?'}).getByRole('button',{name:'Discard review',exact:true}).click()
  await expect(page.getByRole('region',{name:'Custom Preview'})).toHaveCount(0)
  await page.getByRole('link',{name:'Workspace',exact:true}).click()
  await expect(page.locator('.cm-content')).toContainText('Robot Guide')
})

test('unavailable source offers optional local HTML fallback and retains the source URL',async({page})=>{
  await page.route('**/api/import',route=>route.fulfill({status:502,json:{error:'The source website returned HTTP 403. Try a different public page.'}}))
  await page.goto('/import')
  await page.getByLabel('Page URL',{exact:true}).fill('https://blocked.example.com/docs/page')
  await page.getByRole('button',{name:'Convert to Markdown',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('source website returned HTTP 403')
  await page.getByRole('button',{name:'Import saved or pasted HTML'}).click()
  await expect(page.getByLabel('Source URL',{exact:false})).toHaveValue('https://blocked.example.com/docs/page')
  await page.getByLabel('Paste HTML',{exact:true}).fill('<main><h1>Local fallback</h1><p>Saved article.</p></main>')
  await page.getByRole('button',{name:'Parse & review'}).click()
  await expect(page.locator('.markdown-content h1')).toHaveText('Local fallback')
})

test('one shared tab bar switches editor and preview together across desktop, reader and mobile',async({page})=>{
  await page.goto('/workspace')
  await page.getByRole('button',{name:'New Markdown file',exact:true}).click()
  await page.locator('.cm-content').fill('# First buffer')
  await page.keyboard.press('Control+Alt+n')
  const tabs=page.getByRole('tablist',{name:'Open documents'})
  await expect(page.getByRole('tablist')).toHaveCount(1)
  await expect(tabs.getByRole('tab')).toHaveCount(2)
  await page.locator('.cm-content').fill('# Second buffer')
  await expect(page.locator('.markdown-content h1')).toHaveText('Second buffer')
  await tabs.getByRole('button',{name:'Untitled.md',exact:true}).click()
  await expect(page.locator('.markdown-content h1')).toHaveText('First buffer')
  await expect(page.locator('.cm-content')).toContainText('First buffer')
  await tabs.getByRole('button',{name:'Untitled-2.md',exact:true}).dblclick()
  await page.getByRole('textbox',{name:'Document filename'}).fill('Second name')
  const download=page.waitForEvent('download');await page.keyboard.press('Control+s')
  expect((await download).suggestedFilename()).toBe('Second name.md')
  await page.locator('.cm-content').focus()
  const saved=page.waitForEvent('download');await page.keyboard.press('Control+s')
  expect((await saved).suggestedFilename()).toBe('Second name.md')
  await expect(page.locator('.markdown-content h1')).toHaveText('Second buffer')
  await page.getByRole('button',{name:'Reader mode',exact:true}).click()
  await expect(page.getByRole('tablist')).toHaveCount(1)
  await tabs.getByRole('button',{name:'Untitled.md',exact:true}).click()
  await expect(page.locator('.markdown-content h1')).toHaveText('First buffer')
  await page.getByRole('button',{name:'Exit reader mode',exact:true}).click()
  await expect(page.locator('.cm-content')).toContainText('First buffer')
  await page.setViewportSize({width:390,height:844})
  const sections=page.getByRole('navigation',{name:'Workspace sections'})
  await sections.getByRole('button',{name:'Preview',exact:true}).click()
  await expect(page.getByRole('tablist')).toHaveCount(1)
  await tabs.getByRole('button',{name:'Second name.md',exact:true}).click()
  await expect(page.locator('.markdown-content h1')).toHaveText('Second buffer')
  await sections.getByRole('button',{name:'Edit',exact:true}).click()
  await expect(page.locator('.cm-content')).toContainText('Second buffer')
  await page.getByRole('button',{name:'New Markdown file',exact:true}).click()
  await expect(tabs.getByRole('tab')).toHaveCount(3)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
})


for (const theme of ['light', 'dark'] as const) {
  test(`themed unsaved dialog preserves edits on cancel and closes only the chosen tab (${theme})`, async ({page}) => {
    const nativeDialogs: string[] = [], downloads: string[] = []
    page.on('dialog', dialog => {nativeDialogs.push(dialog.type()); void dialog.dismiss()})
    page.on('download', download => downloads.push(download.suggestedFilename()))
    await page.goto('/workspace')
    await page.evaluate(async theme => {const {useSettingsStore}=await import('/src/stores/settingsStore.ts');useSettingsStore.getState().setTheme(theme)}, theme)
    await page.getByRole('button', {name:'New Markdown file',exact:true}).click()
    await page.locator('.cm-content').fill('# Keep this draft')
    await page.getByRole('button', {name:'New Markdown file',exact:true}).click()
    await page.locator('.cm-content').fill('# Other draft')
    const tabs=page.getByRole('tablist', {name:'Open documents'})
    const close=page.getByRole('button', {name:'Close Untitled.md',exact:true})
    await close.click()
    const dialog=page.getByRole('dialog', {name:'Discard unsaved changes?'})
    const keep=dialog.getByRole('button', {name:'Keep editing',exact:true})
    await expect(dialog).toBeVisible()
    await expect(dialog).toContainText('Untitled.md')
    await expect(keep).toBeFocused()
    await expect(dialog).toHaveCSS('background-color', theme==='dark'?'rgb(22, 23, 31)':'rgb(255, 255, 255)')
    // Focus stays in the modal; shortcuts must not create files or save behind it.
    for(let i=0;i<5;i++) {
      await page.keyboard.press('Tab')
      expect(await dialog.evaluate(element=>element.contains(document.activeElement))).toBe(true)
    }
    await page.keyboard.press('Control+Alt+n')
    await page.keyboard.press('Control+s')
    await expect(tabs.getByRole('tab')).toHaveCount(2)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(close).toBeFocused()
    await tabs.getByRole('button', {name:'Untitled.md',exact:true}).click()
    await expect(page.locator('.cm-content')).toContainText('Keep this draft')
    await close.click()
    await keep.click()
    await expect(tabs.getByRole('tab')).toHaveCount(2)
    await close.click()
    await dialog.getByRole('button', {name:'Cancel and keep editing',exact:true}).click()
    await expect(close).toBeFocused()
    await close.click()
    await page.screenshot({path:`.tmp/confirm-${theme}-desktop.png`})
    await page.setViewportSize({width:390,height:844})
    const bounds=await dialog.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(16)
    expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(374)
    expect(bounds!.height).toBeLessThan(812)
    await page.screenshot({path:`.tmp/confirm-${theme}-mobile.png`})
    await dialog.getByRole('button', {name:'Discard changes',exact:true}).click()
    await expect(dialog).toHaveCount(0)
    await expect(tabs.getByRole('tab')).toHaveCount(1)
    await expect(tabs.getByRole('button', {name:'Untitled-2.md',exact:true})).toBeVisible()
    await page.setViewportSize({width:1440,height:1000})
    await expect(page.locator('.cm-content')).toContainText('Other draft')
    expect(nativeDialogs).toEqual([])
    expect(downloads).toEqual([])
  })
}

test('replacement import confirmation retains the review until explicitly accepted', async ({page})=>{
  await page.goto('/import')
  await page.getByRole('button',{name:/^HTML/}).click()
  await page.getByLabel('Paste HTML',{exact:true}).fill('<main><h1>Original review</h1></main>')
  await page.getByRole('button',{name:'Parse & review',exact:true}).click()
  await expect(page.locator('.markdown-content h1')).toHaveText('Original review')
  await page.getByText('Import another source',{exact:true}).click()
  await page.getByRole('button',{name:/^HTML/}).click()
  await page.getByLabel('Paste HTML',{exact:true}).fill('<main><h1>Replacement review</h1></main>')
  await page.getByRole('button',{name:'Parse & review',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Replace this import review?'})
  await dialog.getByRole('button',{name:'Keep reviewing',exact:true}).click()
  await expect(page.locator('.markdown-content h1')).toHaveText('Original review')
  await page.getByRole('button',{name:'Parse & review',exact:true}).click()
  await dialog.getByRole('button',{name:'Replace review',exact:true}).click()
  await expect(page.locator('.markdown-content h1')).toHaveText('Replacement review')
})


test('direct Markdown result is clean, copyable and accessible on mobile without export navigation',async({page,context})=>{
  await context.grantPermissions(['clipboard-read','clipboard-write'])
  await page.route('**/api/import',route=>route.fulfill({json:{url:'https://example.com/guide',html:'<main><h1>Professional guide</h1><h2 id="setup"><div></div><span>Setup</span></h2><p>Follow <a href="#setup">Setup</a> and use <code>npm install</code>.</p></main>'}}))
  await page.goto('/import')
  await page.getByLabel('Page URL',{exact:true}).fill('https://example.com/guide')
  await page.getByRole('button',{name:'Convert to Markdown',exact:true}).click()
  await expect(page.locator('.markdown-content h2')).toHaveText('Setup')
  await expect(page.getByRole('checkbox',{name:'Keep block 1',exact:true})).toHaveCount(0)
  await expect(page.getByText(/Internal heading link needs review/)).toHaveCount(0)
  await page.getByRole('button',{name:'Copy Markdown',exact:true}).click()
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('## Setup')
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download .md',exact:true}).click()
  const file=await download;expect(file.suggestedFilename()).toBe('Professional guide.md')
  expect(readFileSync((await file.path())!,'utf8')).toContain('## Setup')
  for(const theme of ['light','dark'] as const){
    await page.evaluate(async theme=>{const {useSettingsStore}=await import('/src/stores/settingsStore.ts');useSettingsStore.getState().setTheme(theme)},theme)
    await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:`.tmp/import-redesign-${theme}-desktop.png`})
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:`.tmp/import-redesign-${theme}-mobile.png`})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
    const bounds=await page.getByRole('button',{name:'Download .md',exact:true}).boundingBox()
    expect(bounds!.y+bounds!.height).toBeLessThan(844)
  }
})

test('paged large review downloads every block including sections outside the visible preview',async({page})=>{
  await page.goto('/import')
  await page.getByRole('button',{name:'HTML',exact:true}).click()
  await page.getByLabel('Paste HTML',{exact:true}).fill('<main><h1>Long document</h1>'+Array.from({length:205},(_,i)=>`<p>Unique section ${i+1}.</p>`).join('')+'</main>')
  await page.getByRole('button',{name:'Parse & review',exact:true}).click()
  await expect(page.locator('.markdown-content')).not.toContainText('Unique section 205.')
  await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('button',{name:'Next',exact:true}).click()
  await expect(page.locator('.markdown-content')).toContainText('Unique section 205.')
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download .md',exact:true}).click()
  const content=readFileSync((await (await download).path())!,'utf8')
  expect(content).toContain('Unique section 1.');expect(content).toContain('Unique section 205.')
})
