import { test, expect, type Page, type Locator } from '@playwright/test'
import path from 'node:path'
import { existsSync, readFileSync } from 'node:fs'
const corpus = process.env.UM_TEST_CORPUS ?? path.resolve('..', 'documentation')
test.beforeEach(async ({ page }) => { page.on('console', msg => { if (msg.type() === 'error') console.log('BROWSER', msg.text()) }) })
test('shared export and sanitization regression harness', async ({ page }) => {
  await page.goto('/tests/regression.html')
  await expect(page.locator('#summary')).toContainText(/CHECKS PASSED|FAILURES|ERROR/, { timeout: 30000 })
  expect(await page.locator('#results li').filter({hasText:/^FAIL/}).allTextContents()).toEqual([])
  await expect(page.locator('#summary')).toContainText('CHECKS PASSED')
})

async function fallbackPickers(page: Page) {
  await page.addInitScript(() => { Object.defineProperty(window, 'showDirectoryPicker', { value: undefined, configurable: true }); Object.defineProperty(window, 'showOpenFilePicker', { value: undefined, configurable: true }) })
}
async function folder(page: Page) {
  await fallbackPickers(page)
  await page.goto('/')
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Open folder', exact: true }).click()
  await (await chooser).setFiles(corpus)
  await expect(page).toHaveURL(/workspace/)
}
async function choose(page: Page, control: Locator, name: string) {
  await control.click()
  await page.getByRole('option', {name, exact:true}).click()
}
async function pageCount(page: Page) {
  await expect(page.locator('[role=status]').filter({ hasText: /^\d+ pages?$|Preview unavailable/ })).toBeVisible({ timeout: 60000 })
  const error = page.getByRole('alert')
  if (await error.count()) throw new Error(await error.allTextContents().then(t => t.join('\n')))
  await expect(page.locator('[role=status]').filter({ hasText: /^\d+ pages?$/ })).toBeVisible({ timeout: 60000 })
  return Number((await page.locator('[role=status]').filter({ hasText: /^\d+ pages?$/ }).innerText()).split(' ')[0])
}

test('home actions, live example, responsive navigation and compact find/replace', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'Ultimate Markdown on GitHub' })).toHaveAttribute('href', 'https://github.com/shiwamshoryasharma/Ultimate-Markdown')
  await page.getByRole('textbox', { name: 'Try Markdown' }).fill('# Search test\n\nAlpha alpha alphabet.\n\n## End')
  await expect(page.locator('.markdown-content h1')).toHaveText('Search test')
  await page.getByRole('button', { name: 'Open in editor', exact: true }).click()
  const editor = page.locator('.cm-content')
  await editor.click(); await page.keyboard.press('Control+f')
  await page.getByRole('textbox', { name: 'Find', exact: true }).fill('alpha')
  await page.keyboard.press('Enter')
  await expect(page.locator('.um-find-count')).toHaveText('1 of 3')
  const a = await page.locator('.um-find').boundingBox(), b = await page.locator('.cm-editor').boundingBox()
  expect(a!.y - b!.y).toBeLessThan(15); expect(a!.height).toBeLessThan(60)
  await page.getByRole('button', { name: 'Match whole word', exact: true }).click()
  await expect(page.locator('.um-find-count')).toContainText('of 2')
  await page.getByRole('textbox', { name: 'Find', exact: true }).focus(); await page.keyboard.press('Control+h')
  await page.getByRole('textbox', { name: 'Replace', exact: true }).fill('Beta')
  await page.getByRole('button', { name: 'Replace all', exact: true }).click()
  await expect(editor).toContainText('Beta Beta alphabet.')
  await page.getByRole('textbox', { name: 'Find', exact: true }).focus(); await page.keyboard.press('Escape')
  await expect(page.locator('.um-find')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('link', { name: 'Home', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({ path: '.tmp/home-mobile.png' })
  await page.getByRole('button', { name: /Markdown to PDF/ }).click()
  await expect(page.getByRole('button', { name: 'PDF', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('single file images can be connected without losing edits or following linked documents', async ({ page }) => {
  test.skip(!existsSync(corpus), 'Set UM_TEST_CORPUS to the read-only documentation folder.')
  await fallbackPickers(page); await page.goto('/')
  const chooser = page.waitForEvent('filechooser'); await page.getByRole('button', { name: 'Open Markdown', exact: true }).click()
  await (await chooser).setFiles(path.join(corpus, '03-factory-home.md'))
  await expect(page.getByRole('button', { name: 'Connect image folder', exact: true })).toBeVisible()
  const next = page.waitForEvent('filechooser'); await page.getByRole('button', { name: 'Connect image folder', exact: true }).click()
  await (await next).setFiles(corpus)
  await expect(page.locator('.markdown-content img').first()).toBeVisible()
  await expect.poll(() => page.locator('.markdown-content img').first().evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBeTruthy()
  await page.getByRole('link', { name: 'Converter', exact: true }).click()
  await expect(page.getByText('1 document in export order')).toBeVisible({ timeout: 30000 })
  expect(await pageCount(page)).toBeGreaterThan(1)
  const frame = page.frameLocator('iframe[title="Paginated export preview"]')
  await expect(frame.locator('img').first()).toBeVisible()
})

test('broken links are repaired once; real manual paginates with themes and 1–3 columns', async ({ page }) => {
  test.skip(!existsSync(corpus), 'Set UM_TEST_CORPUS to the read-only documentation folder.')
  await folder(page)
  await page.getByRole('link', { name: 'Converter', exact: true }).click()
  await page.getByRole('button', { name: 'PDF', exact: true }).click()
  const repair = page.getByRole('combobox', { name: 'Replacement for 03-factory-brain.md from 01-introduction.md' })
  await expect(repair).toBeVisible({ timeout: 30000 })
  await expect(repair).toContainText('02-system-overview.md')
  await expect(page.getByText('4 documents in export order')).toBeVisible()
  // Remove a mapping to exercise the generic repair flow as well as the approved profile.
  await choose(page, repair, 'Choose a replacement…')
  await expect(page.getByRole('heading', {name:'Choose where the manual continues'})).toBeVisible()
  await choose(page, repair, '02-system-overview.md')
  const second = page.getByRole('combobox', { name: 'Replacement for 04-factory-brain.md from 03-factory-home.md' })
  await expect(second).toBeVisible({ timeout: 30000 }); await choose(page, second, '04-getting-started.md')
  const third = page.getByRole('combobox', { name: 'Replacement for 05-factory-brain.md from 04-getting-started.md' })
  await expect(third).toBeVisible({ timeout: 30000 }); await choose(page, third, 'End the chain here')
  await expect(page.getByText('4 documents in export order')).toBeVisible()
  const count = await pageCount(page); expect(count).toBeGreaterThan(4)
  const preview = page.frameLocator('iframe[title="Paginated export preview"]')
  expect(await preview.locator('.pagedjs_page').count()).toBe(count)
  await page.getByRole('button', { name: 'Design', exact: true }).click()
  await page.getByRole('button', { name: 'Parchment theme' }).click()
  await pageCount(page)
  await expect(preview.locator('.pagedjs_page').first()).toHaveCSS('background-color', 'rgb(255, 248, 220)')
  await page.getByRole('spinbutton', { name: 'Heading 1 (pt)', exact: true }).fill('14')
  await pageCount(page)
  await expect(preview.locator('h1').first()).toHaveCSS('font-size', '18.6667px')
  for (const columns of [2, 3]) {
    await page.evaluate(async (columns) => { const { useConversionStore } = await import('/src/stores/conversionStore.ts'); useConversionStore.getState().update({ columns }) }, columns)
    await pageCount(page)
    await expect(preview.locator('.export-section').first()).toHaveCSS('column-count', String(columns))
    const content = await preview.locator('.pagedjs_pages').innerText()
    expect(content).toContain('Before Moving Forward')
  }
  await page.screenshot({ path: '.tmp/manual-columns.png' })
})

test('synthetic page boundaries produce four pages plus two pages, with selectable PDF text', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(async () => {
    const sections = (letter: string, n: number) => Array.from({ length: n }, (_, i) => `<div style="${i ? 'break-before:page;' : ''}"><h1>${letter} page ${i + 1}</h1><p>Selectable ${letter} content ${i + 1}.</p></div>`).join('\n\n')
    const entries = [['A.md', sections('A', 4) + '\n\n**Previous:** [A](A.md) || **Next:** [B](B.md)'], ['B.md', sections('B', 2) + '\n\n[Next](A.md)']]
    const transfer = new DataTransfer()
    entries.forEach(([name, content]) => { const file = new File([content], name); Object.defineProperty(file, 'webkitRelativePath', { value: 'Synthetic/' + name }); transfer.items.add(file) })
    document.querySelector('textarea')!.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: transfer }))
  })
  await expect(page).toHaveURL(/workspace/)
  await page.getByRole('link', { name: 'Converter', exact: true }).click()
  expect(await pageCount(page)).toBe(6)
  const frame = page.frameLocator('iframe[title="Paginated export preview"]')
  for (let i = 0; i < 6; i++) await expect(frame.locator('.pagedjs_page').nth(i)).toContainText(i < 4 ? `A page ${i + 1}` : `B page ${i - 3}`)
  await expect(page.getByRole('button', { name: 'Print / Save PDF' })).toBeEnabled()
  const html = await frame.locator('html').evaluate((root) => { const clone = root.cloneNode(true) as HTMLElement; clone.querySelectorAll('script').forEach(el => el.remove()); return '<!DOCTYPE html>' + clone.outerHTML })
  const printPage = await page.context().newPage()
  await printPage.setContent(html)
  const pdf = await printPage.pdf({ preferCSSPageSize: true, printBackground: true, path: '.tmp/six-pages.pdf' })
  expect(pdf.toString('latin1').match(/\/Type\s*\/Page\b/g)?.length).toBe(6)
  await printPage.close()
  const extraction = await page.evaluate(async (data) => {
    const pdfjs = await import('/node_modules/pdfjs-dist/build/pdf.mjs')
    pdfjs.GlobalWorkerOptions.workerSrc = '/node_modules/pdfjs-dist/build/pdf.worker.mjs'
    const task = pdfjs.getDocument({ data: new Uint8Array(data) })
    const doc = await task.promise
    const pages = []
    for (let n = 1; n <= doc.numPages; n++) pages.push((await (await doc.getPage(n)).getTextContent()).items.map(item => 'str' in item ? item.str : '').join(' '))
    await task.destroy()
    return pages
  }, Array.from(pdf))
  expect(extraction).toHaveLength(6)
  expect(extraction[0]).toContain('Selectable A content 1')
  expect(extraction[5]).toContain('Selectable B content 2')
})

test('navigation adapts to Markdown and HTML layouts without replacing ordinary content', async ({page})=>{
  await page.goto('/')
  const input=page.getByRole('textbox',{name:'Try Markdown'})
  const examples=[
    '> **Previous:** [Start](start.md) || **Next:** [Finish](finish.md)',
    '**NEXT** → [Finish](finish.md)\n\n**prev** ← [Start](start.md)',
    '- Back: [Start](start.md)\n- Continue: [Finish](finish.md)',
    '[← Start](start.md) · [Finish →](finish.md)',
    '[Previous: Start](start.md) / [Next: Finish](finish.md)',
    '<div><strong>Next：</strong><a href="finish.md">Finish</a><br><b>Previous：</b><a href="start.md">Start</a></div>',
    '| Previous | Next |\n| --- | --- |\n| [Start](start.md) | [Finish](finish.md) |',
    'Previous: [Start][p] || Next: [Finish][n]\n\n[p]: start.md\n[n]: finish.md',
  ]
  for(const example of examples) {
    await input.fill('## Document Navigation\n\n'+example)
    await expect(page.getByRole('navigation',{name:'Document navigation'})).toHaveCount(1)
    const nav=page.getByRole('navigation',{name:'Document navigation'})
    await expect(nav.getByRole('button',{name:'Previous: Start',exact:true})).toBeDisabled()
    await expect(nav.getByRole('button',{name:'Next: Finish',exact:true})).toBeDisabled()
    await expect(nav.getByRole('button',{name:'Top',exact:true})).toBeVisible()
  }
  await input.fill('Read the next section in [this guide](finish.md) for more detail.\n\n```md\nPrevious: [Start](start.md) || Next: [Finish](finish.md)\n```')
  await expect(page.locator('.um-document-nav')).toHaveCount(0)
  await expect(page.locator('.markdown-content')).toContainText('for more detail.')
})

test('manual navigation cards, document jump and top/bottom work in light, dark and narrow layouts', async ({page})=>{
  test.skip(!existsSync(corpus),'Set UM_TEST_CORPUS to the read-only documentation folder.')
  await folder(page)
  let nav=page.getByRole('navigation',{name:'Document navigation'})
  await choose(page, nav.getByRole('combobox',{name:'Jump to document'}), '03-factory-home.md')
  await expect(nav.getByRole('button',{name:'Previous: System Overview'})).toBeEnabled()
  await expect(nav.getByRole('button',{name:'Next: Getting started'})).toBeEnabled()
  await nav.scrollIntoViewIfNeeded()
  await page.screenshot({path:'.tmp/navigation-light.png'})
  await page.evaluate(()=>document.documentElement.dataset.theme='dark')
  await page.screenshot({path:'.tmp/navigation-dark.png'})
  await nav.getByRole('button',{name:'Next: Getting started'}).click()
  await expect(nav.getByRole('button',{name:'Next: End of manual'})).toBeDisabled()
  await expect(nav.getByRole('combobox',{name:'Jump to document'})).toContainText('04-getting-started.md')
  await choose(page, nav.getByRole('combobox',{name:'Jump to document'}), '02-system-overview.md')
  await expect(nav.getByRole('button',{name:'Next: HOME'})).toBeEnabled()
  await nav.getByRole('button',{name:'Top',exact:true}).click()
  await expect.poll(()=>page.locator('.markdown-content h1').first().evaluate(el=>el.getBoundingClientRect().top)).toBeLessThan(500)
  await nav.getByRole('button',{name:'Bottom',exact:true}).click()
  await expect(nav).toBeInViewport()
  await page.setViewportSize({width:390,height:844})
  if (await page.getByRole('button',{name:'Preview',exact:true}).isVisible()) await page.getByRole('button',{name:'Preview',exact:true}).click()
  await nav.scrollIntoViewIfNeeded()
  const cards=nav.locator('.um-document-nav__card')
  const first=await cards.nth(0).boundingBox(),second=await cards.nth(1).boundingBox()
  expect(second!.y).toBeGreaterThan(first!.y+first!.height)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({path:'.tmp/navigation-mobile.png'})
})


test('settings cards persist preferences, update the live preview and use themed keyboard menus', async ({page}) => {
  await page.goto('/settings')
  await expect(page.getByRole('navigation', {name:'Settings categories'}).getByRole('button')).toHaveCount(5)
  await page.getByRole('button',{name:'Midnight',exact:true}).click()
  await page.getByRole('switch',{name:'Reduce motion'}).click()
  await expect(page.locator('html')).toHaveAttribute('data-reduced-motion','true')
  await page.screenshot({path:'.tmp/settings-dark.png'})
  await page.getByRole('button',{name:'Reading Type & tables'}).click()
  await page.getByRole('button',{name:'Dense documents'}).click()
  await expect(page.getByRole('spinbutton',{name:'Reading font size'})).toHaveValue('14')
  await expect(page.locator('.um-table')).toHaveAttribute('data-density','compact')
  const density = page.getByRole('combobox',{name:'Table density'})
  await density.focus(); await page.keyboard.press('Enter'); await page.keyboard.press('Home'); await page.keyboard.press('Enter')
  await expect(page.locator('.um-table')).toHaveAttribute('data-density','comfortable')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.getByRole('button',{name:'Reading Type & tables'}).click()
  await expect(page.getByRole('spinbutton',{name:'Reading font size'})).toHaveValue('14')
  await density.click()
  await expect(page.getByRole('listbox')).toBeInViewport()
  await page.screenshot({path:'.tmp/settings-dropdown-dark.png'})
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Appearance Theme & motion'}).click()
  await page.getByRole('button',{name:'Daylight',exact:true}).click()
  await page.screenshot({path:'.tmp/settings-light.png'})
  await page.getByRole('button',{name:'Media Images & video'}).click()
  await page.getByRole('switch',{name:'Image captions'}).click()
  await page.reload()
  await page.getByRole('button',{name:'Media Images & video'}).click()
  await expect(page.getByRole('switch',{name:'Image captions'})).toHaveAttribute('aria-checked','false')
  await page.getByRole('button',{name:'Export Page defaults'}).click()
  await choose(page,page.getByRole('combobox',{name:'Default paper size'}),'Letter')
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('ultimate-markdown/conversion-v1')!).state.settings.pageSize)).toBe('Letter')
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('navigation',{name:'Settings categories'})).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({path:'.tmp/settings-mobile.png'})
  await expect(page.locator('select')).toHaveCount(0)
})

test('modern tables copy and download; images zoom; themed media controls play, seek and go fullscreen', async ({page,context}) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await context.grantPermissions(['clipboard-read','clipboard-write'])
  await page.route('https://media.example/image.png',route=>route.fulfill({contentType:'image/png',body:readFileSync('public/ultimate-markdown-logo.png')}))
  await page.route('https://media.example/demo.mp4',route=>{
    const bytes=readFileSync('tests/fixtures/player-demo.mp4'), range=route.request().headers().range?.match(/bytes=(\d+)-(\d*)/)
    if (!range) return route.fulfill({contentType:'video/mp4',headers:{'Accept-Ranges':'bytes','Content-Length':String(bytes.length)},body:bytes})
    const start=Number(range[1]),end=range[2]?Math.min(Number(range[2]),bytes.length-1):bytes.length-1
    return route.fulfill({status:206,contentType:'video/mp4',headers:{'Accept-Ranges':'bytes','Content-Range':`bytes ${start}-${end}/${bytes.length}`,'Content-Length':String(end-start+1)},body:bytes.subarray(start,end+1)})
  })
  await page.goto('/')
  await page.getByRole('textbox',{name:'Try Markdown'}).fill('# Rich document\n\n| Name | Value |\n| :--- | ---: |\n| Engine | Ready |\n| Formula | =1+1 |\n\n![Architecture](https://media.example/image.png)\n\n<video src="https://media.example/demo.mp4" loop></video>')
  const table = page.locator('.um-table')
  await expect(table.locator('th').first()).toHaveText('Name')
  await expect(table.locator('th').last()).toHaveCSS('text-align','right')
  await table.getByRole('button',{name:'Copy table',exact:true}).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('Engine\tReady')
  const downloadEvent=page.waitForEvent('download'); await table.getByRole('button',{name:'Download table as CSV'}).click()
  const csv=readFileSync((await (await downloadEvent).path())!,'utf8'); expect(csv).toContain('"Engine","Ready"'); expect(csv).toContain("'=1+1")
  const expand=page.getByRole('button',{name:'Expand image: Architecture'})
  await expand.click()
  await expect(page.getByRole('dialog',{name:'Architecture'})).toBeVisible()
  await page.getByRole('button',{name:'Zoom in',exact:true}).click()
  await expect(page.getByLabel('Image zoom')).toHaveText('125%')
  await page.screenshot({path:'.tmp/image-viewer.png'})
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(expand).toBeFocused()
  const player=page.getByRole('group',{name:'Video player'}), video=player.locator('video')
  await expect.poll(()=>video.evaluate((el:HTMLVideoElement)=>el.readyState)).toBeGreaterThan(0)
  await player.getByRole('button',{name:'Play video',exact:true}).click()
  await expect(player.getByRole('button',{name:'Pause video',exact:true})).toBeVisible()
  await player.getByRole('button',{name:'Pause video',exact:true}).click()
  await player.getByRole('slider',{name:'Video position'}).fill('2')
  await expect.poll(()=>video.evaluate((el:HTMLVideoElement)=>el.currentTime)).toBeCloseTo(2,0)
  await choose(page,player.getByRole('combobox',{name:'Playback speed'}),'1.5×')
  expect(await video.evaluate((el:HTMLVideoElement)=>el.playbackRate)).toBe(1.5)
  await player.getByRole('button',{name:'Mute video'}).click()
  expect(await video.evaluate((el:HTMLVideoElement)=>el.muted)).toBeTruthy()
  await player.getByRole('button',{name:'Toggle video fullscreen'}).click()
  await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBeTruthy()
  await player.getByRole('combobox',{name:'Playback speed'}).click()
  await expect(page.getByRole('listbox')).toBeVisible()
  await page.getByRole('option',{name:'1×',exact:true}).click()
  await page.evaluate(()=>document.exitFullscreen())
  await page.screenshot({path:'.tmp/media-light.png'})
  await page.evaluate(()=>document.documentElement.dataset.theme='dark')
  await player.getByRole('combobox',{name:'Playback speed'}).click()
  await page.screenshot({path:'.tmp/media-dropdown-dark.png'})
  await page.keyboard.press('Escape')
  await page.setViewportSize({width:390,height:844})
  await table.scrollIntoViewIfNeeded()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({path:'.tmp/table-mobile.png'})
  await expect(page.locator('select')).toHaveCount(0)
  expect(errors).toEqual([])
})
